-- Script de datos iniciales para suscripciones
-- Inserta diferentes planes de suscripción con características variadas

-- Plan Básico
INSERT INTO suscripciones (
    nombre, 
    descripcion, 
    precio_original, 
    porcentaje_descuento, 
    precio_final,
    duracion_dias, 
    numero_solicitudes_incluidas, 
    soporte_prioritario, 
    destacado, 
    activo, 
    orden_visualizacion, 
    color_hexadecimal, 
    icono, 
    fecha_creacion, 
    fecha_modificacion, 
    creado_por
) VALUES (
    'Plan Básico',
    'Plan perfecto para comenzar. Ideal para usuarios que necesitan servicios ocasionales con acceso a todas las categorías disponibles.',
    4990.00,
    0.00,
    4990.00,
    30,
    5,
    false,
    false,
    true,
    1,
    '#4CAF50',
    'verified_user',
    NOW(),
    NOW(),
    'sistema'
);

-- Plan Estándar (con descuento de lanzamiento)
INSERT INTO suscripciones (
    nombre, 
    descripcion, 
    precio_original, 
    porcentaje_descuento, 
    precio_final,
    duracion_dias, 
    numero_solicitudes_incluidas, 
    soporte_prioritario, 
    destacado, 
    activo, 
    orden_visualizacion, 
    color_hexadecimal, 
    icono, 
    fecha_creacion, 
    fecha_modificacion, 
    creado_por
) VALUES (
    'Plan Estándar',
    'El plan más popular. Incluye más solicitudes mensuales y soporte prioritario. Perfecto para usuarios frecuentes que necesitan respuesta rápida.',
    9990.00,
    15.00,
    8491.50,
    30,
    15,
    true,
    true,
    true,
    2,
    '#2196F3',
    'star',
    NOW(),
    NOW(),
    'sistema'
);

-- Plan Premium (con descuento especial)
INSERT INTO suscripciones (
    nombre, 
    descripcion, 
    precio_original, 
    porcentaje_descuento, 
    precio_final,
    duracion_dias, 
    numero_solicitudes_incluidas, 
    soporte_prioritario, 
    destacado, 
    activo, 
    orden_visualizacion, 
    color_hexadecimal, 
    icono, 
    fecha_creacion, 
    fecha_modificacion, 
    creado_por
) VALUES (
    'Plan Premium',
    'Para usuarios exigentes. Solicitudes ilimitadas, soporte 24/7, acceso prioritario a técnicos destacados y descuentos exclusivos en servicios premium.',
    19990.00,
    20.00,
    15992.00,
    30,
    NULL,
    true,
    true,
    true,
    3,
    '#FF9800',
    'workspace_premium',
    NOW(),
    NOW(),
    'sistema'
);

-- Plan Trimestral Básico
INSERT INTO suscripciones (
    nombre, 
    descripcion, 
    precio_original, 
    porcentaje_descuento, 
    precio_final,
    duracion_dias, 
    numero_solicitudes_incluidas, 
    soporte_prioritario, 
    destacado, 
    activo, 
    orden_visualizacion, 
    color_hexadecimal, 
    icono, 
    fecha_creacion, 
    fecha_modificacion, 
    creado_por
) VALUES (
    'Plan Trimestral Básico',
    'Ahorra con el plan trimestral. 3 meses de acceso con descuento especial. Ideal para planificar servicios a largo plazo.',
    14970.00,
    10.00,
    13473.00,
    90,
    15,
    false,
    false,
    true,
    4,
    '#4CAF50',
    'calendar_today',
    NOW(),
    NOW(),
    'sistema'
);

-- Plan Trimestral Premium (más popular para ahorro)
INSERT INTO suscripciones (
    nombre, 
    descripcion, 
    precio_original, 
    porcentaje_descuento, 
    precio_final,
    duracion_dias, 
    numero_solicitudes_incluidas, 
    soporte_prioritario, 
    destacado, 
    activo, 
    orden_visualizacion, 
    color_hexadecimal, 
    icono, 
    fecha_creacion, 
    fecha_modificacion, 
    creado_por
) VALUES (
    'Plan Trimestral Premium',
    '¡Mejor oferta! 3 meses de Plan Premium con 25% de descuento. Solicitudes ilimitadas, soporte VIP y beneficios exclusivos durante todo el trimestre.',
    59970.00,
    25.00,
    44977.50,
    90,
    NULL,
    true,
    true,
    true,
    5,
    '#FF9800',
    'emoji_events',
    NOW(),
    NOW(),
    'sistema'
);

-- Plan Anual Estándar (mejor relación precio/beneficio)
INSERT INTO suscripciones (
    nombre, 
    descripcion, 
    precio_original, 
    porcentaje_descuento, 
    precio_final,
    duracion_dias, 
    numero_solicitudes_incluidas, 
    soporte_prioritario, 
    destacado, 
    activo, 
    orden_visualizacion, 
    color_hexadecimal, 
    icono, 
    fecha_creacion, 
    fecha_modificacion, 
    creado_por
) VALUES (
    'Plan Anual Estándar',
    'Máximo ahorro anual. 12 meses por el precio de 8. Incluye soporte prioritario y beneficios exclusivos para suscriptores anuales.',
    119880.00,
    30.00,
    83916.00,
    365,
    180,
    true,
    true,
    true,
    6,
    '#2196F3',
    'military_tech',
    NOW(),
    NOW(),
    'sistema'
);

-- Plan Anual Premium (máximo nivel)
INSERT INTO suscripciones (
    nombre, 
    descripcion, 
    precio_original, 
    porcentaje_descuento, 
    precio_final,
    duracion_dias, 
    numero_solicitudes_incluidas, 
    soporte_prioritario, 
    destacado, 
    activo, 
    orden_visualizacion, 
    color_hexadecimal, 
    icono, 
    fecha_creacion, 
    fecha_modificacion, 
    creado_por
) VALUES (
    'Plan Anual Premium Gold',
    'Experiencia VIP total. 12 meses de acceso ilimitado, gestor de cuenta dedicado, descuentos en todos los servicios, acceso anticipado a nuevas funciones y soporte 24/7 prioritario.',
    239880.00,
    35.00,
    155922.00,
    365,
    NULL,
    true,
    true,
    true,
    7,
    '#FFD700',
    'diamond',
    NOW(),
    NOW(),
    'sistema'
);

-- Plan Empresarial
INSERT INTO suscripciones (
    nombre, 
    descripcion, 
    precio_original, 
    porcentaje_descuento, 
    precio_final,
    duracion_dias, 
    numero_solicitudes_incluidas, 
    soporte_prioritario, 
    destacado, 
    activo, 
    orden_visualizacion, 
    color_hexadecimal, 
    icono, 
    fecha_creacion, 
    fecha_modificacion, 
    creado_por
) VALUES (
    'Plan Empresarial',
    'Solución corporativa completa. Múltiples usuarios, facturación centralizada, reportes detallados, API access, gestor de cuenta dedicado y términos de servicio personalizados.',
    99990.00,
    10.00,
    89991.00,
    30,
    NULL,
    true,
    false,
    true,
    8,
    '#9C27B0',
    'business_center',
    NOW(),
    NOW(),
    'sistema'
);

-- Plan Prueba (gratis por tiempo limitado)
INSERT INTO suscripciones (
    nombre, 
    descripcion, 
    precio_original, 
    porcentaje_descuento, 
    precio_final,
    duracion_dias, 
    numero_solicitudes_incluidas, 
    soporte_prioritario, 
    destacado, 
    activo, 
    orden_visualizacion, 
    color_hexadecimal, 
    icono, 
    fecha_creacion, 
    fecha_modificacion, 
    creado_por
) VALUES (
    'Plan Prueba Gratis',
    'Prueba nuestra plataforma sin compromiso. 7 días de acceso completo con 3 solicitudes incluidas. No se requiere tarjeta de crédito.',
    4990.00,
    100.00,
    0.00,
    7,
    3,
    false,
    true,
    true,
    0,
    '#607D8B',
    'free_breakfast',
    NOW(),
    NOW(),
    'sistema'
);
